#!/usr/bin/env bash

echo "Creating bucket $1"

if [ -z "$1" ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi

bucket_name="$1"

aws s3api create-bucket \
--bucket $bucket_name \
--create-bucket-configuration LocationConstraint=eu-west-2 \
--query 'Location' \
--output text